# Generated by Django 4.1 on 2022-09-13 07:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_category', models.IntegerField(choices=[(2, 'Km2'), (3, 'Km3'), (5, 'Km5'), (7, 'Km7')], help_text='경로 길이')),
                ('path_coordinate', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, help_text='경로 위경도 좌표 배열', null=True, size=None)),
                ('path_length', models.FloatField(default=0, help_text='실제 경로 거리')),
                ('maybe_time', models.IntegerField(default=0, help_text='예상 소요시간(분)')),
                ('mission', models.CharField(blank=True, help_text='미션', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spot_coordinate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), blank=True, help_text='스팟 위경도', null=True, size=None)),
                ('spot_type', models.IntegerField(choices=[(0, 'Sol Spot'), (1, 'Pick Spot')], help_text='스팟 종류(0:솔방울정산소, 1:픽스팟)')),
            ],
        ),
    ]
