# Generated by Django 4.1.1 on 2022-09-16 10:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='경로 이름', max_length=20)),
                ('length_category', models.IntegerField(choices=[(2, 'Km2'), (3, 'Km3'), (5, 'Km5')], help_text='경로 거리 범주')),
                ('geojson', models.TextField(blank=True, help_text='경로 geojson (문자열)', null=True)),
                ('length', models.FloatField(default=0, help_text='실제 경로 거리')),
                ('maybe_time', models.IntegerField(default=0, help_text='예상 소요시간(분)')),
                ('mission', models.CharField(blank=True, help_text='미션', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='스팟 이름', max_length=20)),
                ('coordinate', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), help_text='스팟 위경도', size=None)),
                ('type', models.IntegerField(choices=[(0, 'Sol Spot'), (1, 'Pick Spot')], help_text='스팟 종류(0:솔방울정산소, 1:픽스팟)')),
            ],
        ),
    ]
