# Generated by Django 4.1.1 on 2022-09-16 12:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='geojson',
        ),
        migrations.AddField(
            model_name='path',
            name='coordinate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=40), blank=True, help_text='경로 지점 위경도', null=True, size=None),
        ),
    ]
