# Generated by Django 4.1 on 2022-09-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='path_length',
            field=models.IntegerField(choices=[(1, 'Km1'), (3, 'Km3'), (5, 'Km5')], default=1, help_text='경로 길이(1:1km, 3:3km, 5:5km)'),
            preserve_default=False,
        ),
    ]
