# Generated by Django 4.1 on 2022-09-14 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='path_coordinate',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='spot_coordinate',
        ),
        migrations.AddField(
            model_name='path',
            name='path_geojson',
            field=models.TextField(blank=True, help_text='경로 geojson (문자열)', null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='spot_geojson',
            field=models.TextField(blank=True, help_text='스팟 geojson (문자열)', null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='length_category',
            field=models.IntegerField(choices=[(2, 'Km2'), (3, 'Km3'), (5, 'Km5')], help_text='경로 거리 범주'),
        ),
    ]
