# Generated by Django 4.1 on 2022-09-10 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_path_path_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='path',
            name='id',
        ),
        migrations.AlterField(
            model_name='path',
            name='path_length',
            field=models.IntegerField(choices=[(1, 'Km1'), (3, 'Km3'), (5, 'Km5')], help_text='경로 길이(1:1km, 3:3km, 5:5km)', primary_key=True, serialize=False),
        ),
    ]
