# Generated by Django 4.1 on 2022-09-14 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_rename_path_geojson_path_geojson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='name',
            field=models.CharField(help_text='경로 이름', max_length=20),
        ),
        migrations.AlterField(
            model_name='spot',
            name='name',
            field=models.CharField(help_text='스팟 이름', max_length=20),
        ),
    ]
