# Generated by Django 4.1 on 2022-09-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='region',
            field=models.CharField(default='동작구', help_text='길드 지역', max_length=10),
        ),
    ]
