# Generated by Django 4.1 on 2022-09-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guild', '0002_guild_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='region',
            field=models.CharField(help_text='길드 지역', max_length=10),
        ),
    ]
