# Generated by Django 4.1.1 on 2022-09-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, help_text='날짜')),
                ('point', models.IntegerField(default=0, help_text='포인트')),
                ('garbage', models.FloatField(default=0, help_text='쓰레기양')),
                ('heart_rate', models.IntegerField(default=0, help_text='심박수')),
                ('step_count', models.IntegerField(default=0, help_text='걸음수')),
                ('review', models.IntegerField(default=0, help_text='별점')),
                ('path_id', models.ForeignKey(blank=True, help_text='경로', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='map.path')),
            ],
        ),
    ]
