# Generated by Django 4.1.1 on 2022-09-11 07:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0003_remove_path_id_alter_path_path_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, help_text='날짜', null=True)),
                ('point', models.IntegerField(blank=True, help_text='포인트', null=True)),
                ('garbage', models.FloatField(blank=True, help_text='쓰레기양', null=True)),
                ('path', models.ForeignKey(blank=True, help_text='경로', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='path', to='map.path')),
                ('user', models.ForeignKey(blank=True, help_text='유저', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
