# Generated by Django 4.1 on 2022-09-14 06:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='review',
            field=models.IntegerField(default=0, help_text='별점'),
        ),
        migrations.AddField(
            model_name='activity',
            name='step_count',
            field=models.IntegerField(default=0, help_text='걸음수'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, help_text='날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='garbage',
            field=models.FloatField(default=0, help_text='쓰레기양'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='point',
            field=models.IntegerField(default=0, help_text='포인트'),
        ),
    ]
