# Generated by Django 4.1 on 2022-09-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_review_activity_step_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='heart_rate',
            field=models.IntegerField(default=0, help_text='심박수'),
        ),
    ]
