# Generated by Django 4.1 on 2022-09-14 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_heart_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='path',
            new_name='path_id',
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='user',
            new_name='user_id',
        ),
    ]
